---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-lab
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: s3
    - port: 9001
      targetPort: 9001
      name: console
  clusterIP: None  # Headless service
  selector:
    app: minio